### ISSUE TITLE
Question on Options

### ISSUE THREAD

**Issue by 274188A** [jrdevgit/REDCap-Capture-Form-Save-Submit-Time#2]
i'm not 100% clear what happens when you check a whole lot of the checkboxes - instead of just one...do we need 1 field/option?
Thanks

**Comment by 274188A** [comment]
so i'm assuming now that if you tick multiple boxes, it just records the "first" of those events to occur if you select "only capture" . 
Or if you select the "always capture" then it keeps overwriting those times in the box.

**Comment by jrdevgit** [comment]
> so i'm assuming now that if you tick multiple boxes, it just records the "first" of those events to occur if you select "only capture" .
> Or if you select the "always capture" then it keeps overwriting those times in the box.

Hi John, yes that is correct. "Only capture ... " will capture the time of the first event, depending on the checkboxes you tick, while "Always capture ... " will keep overwriting the time whenever any of the events you ticked is triggered.
